# fly.toml app configuration file generated for tailwings on 2023-05-23T23:44:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tailwings"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "ghcr.io/tailscale/tailscale:latest"

[env]
  TS_EXTRA_ARGS = "--advertise-tags=tag:tailwings --advertise-exit-node"
  TS_HOSTNAME = "fly-${FLY_REGION}"
  TS_TAILSCALED_EXTRA_ARGS = "--port 41641 --state=mem:"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
